# Generated by Django 3.2.8 on 2021-11-27 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
        ('Artigos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigos',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Login.usuarios'),
            preserve_default=False,
        ),
    ]
