# Generated by Django 3.2.8 on 2021-11-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artigos', '0003_alter_artigos_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigos',
            name='genero',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
